# Number of training sessions
sessions: 500

# Size of the board
boardsize: 10

# Path to load the training data from
load: [
  "models/normal/100k_normal",
  "models/normal/200k_normal",
  "models/normal/300k_normal",
  "models/normal/400k_normal",
  "models/normal/500k_normal",
  "models/normal/600k_normal"
]

# Display training progress
# visual: false

# If true, the model doesn't explore
# exploit: true

# If true, the model won't update q-table
dontlearn: true

# Seed for random number generator
seed: 10