# Number of training sessions per epoch
sessions: 100000

# Size of the board default 10
# boardsize: 10

# Path to save the training data to
save: "univ"

# Path to load the training data from
load: "200k_univ"

# Display training progress
# visual: false

# If true, the model doesn't explore
exploit: true

# If true, the model won't update q-table
# dontlearn: false

# If true, the model will wait for user input after each move
# step-by-step: false

# Play the game manually
# manual: false

# Prioritize filling zero values in the q-table
# fill-zeroes: true

# If true, the model can be used for any board size
universal: true

# The number of saved models each trained the specified number of sessions
epochs: 1

# Seed for random number generator
# seed: 10