# Number of training sessions per epoch
sessions: 10

# Size of the board default: 10
boardsize: 15

# ending of the path to save the model
save: "univ"

# Path to load the training data from
# load: ""

# Display training progress
# visual: false

# If true, the model doesn't explore, default: false, if dontlearn is true, exploit is true
exploit: false

# If true, the model won't update q-table
# dontlearn: false

# If true, the model will wait for user input after each move
# step-by-step: false

# Play the game manually
# manual: false

# If true, the model can be used for any board size
universal: true

# The program runs `epochs * sessions` games and saves the model `epoch` times
epochs: 10

# Seed for random number generator
# seed: 10