# Number of training sessions
sessions: 100000

# Size of the board
# boardsize: 10

# Path to save the training data to
save: "300k_normal.json"

# Path to load the training data from
load: "200k_normal.json"

# Display training progress
# visual: false

# If true, the model doesn't explore
exploit: true

# If true, the model won't update q-table
# dontlearn: false

# If true, the model will wait for user input after each move
# step-by-step: false

# Play the game manually
# manual: false

# Prioritize filling zero values in the q-table
# fill-zeroes: false

# Seed for random number generator
# seed: 10